echo "Starting DevOps Application"
echo "Logging enabled"
echo "2 - Line added in main to test conflict"
echo "Line just before adding the temp. debug line"
echo "This line is for first small commit to apply rebase in PART 9"
echo "This line is for second small commit to apply rebase in PART 9"