echo "Starting DevOps Application"
echo "Logging enabled"
echo "2 - Line added in main to test conflict"
echo "Line just before adding the temp. debug line"
echo "Temp. Debug Line (We will revert back to 9a6a050)"